#!/usr/bin/env bash
# setup-local.sh -- one-shot human-facing local-scaffold setup.
#
# Walks a new contributor from "I have a Windows VM" to "I can run the
# test matrix". Prompts for VM details, verifies SSH connectivity,
# probes for required tools, and writes ${CONSUMER_ROOT}/.test-env.
#
# Defaults are pulled from the consumer's ${CONSUMER_ROOT}/harness.toml
# `[vm]` section if present; otherwise the user is prompted with no
# default. After setup, contributors run:
#
#   bash <harness>/scripts/test-windows-matrix.sh
#
# with no env vars or SSH flags.

set -euo pipefail

# shellcheck source=_lib_harness.sh
source "$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)/_lib_harness.sh"

ENV_FILE="${consumer_root}/.test-env"

if [[ ! -f "${harness_toml}" ]]; then
    echo "harness.toml not found at ${harness_toml}." >&2
    echo "  Either run from the consumer repo root, or set HARNESS_TOML=..." >&2
    echo "  See <harness>/docs/consumer-integration.md for the schema." >&2
    exit 2
fi

PROJECT_NAME="$(harness_get_or project.name "consumer-project")"
DEFAULT_HOST="$(harness_get_or vm.host "")"
DEFAULT_KEY="$(harness_get_or vm.ssh_key "")"
DEFAULT_WORKDIR="$(harness_get_or vm.workdir "")"
DEFAULT_IMAGE_DIR="$(harness_get_or vm.image_dir "")"

# Resolve relative SSH key paths against the consumer repo root.
if [[ -n "${DEFAULT_KEY}" && "${DEFAULT_KEY}" != /* ]]; then
    DEFAULT_KEY="$(cd "${consumer_root}" && cd "$(dirname "${DEFAULT_KEY}")" 2>/dev/null && pwd)/$(basename "${DEFAULT_KEY}")" || \
        DEFAULT_KEY="${consumer_root}/${DEFAULT_KEY}"
fi

PRIOR_HOST=""; PRIOR_KEY=""; PRIOR_WORKDIR=""; PRIOR_IMAGES=""
if [[ -f "${ENV_FILE}" ]]; then
    # shellcheck disable=SC1090
    source "${ENV_FILE}"
    PRIOR_HOST="${VM_HOST:-}"
    PRIOR_WORKDIR="${VM_WORKDIR:-}"
    PRIOR_IMAGES="${VM_IMAGE_DIR:-}"
    if [[ "${SSH_OPTS:-}" == *"-i "* ]]; then
        PRIOR_KEY="$(echo "${SSH_OPTS}" | sed -n 's/.*-i \([^ ]*\).*/\1/p')"
    fi
fi

prompt() {
    local var="$1" question="$2" default="${3:-}"
    local input
    if [[ -n "${default}" ]]; then
        read -r -p "${question} [${default}]: " input
        printf -v "${var}" '%s' "${input:-${default}}"
    else
        read -r -p "${question}: " input
        printf -v "${var}" '%s' "${input}"
    fi
}

echo "==============================================================="
echo " ${PROJECT_NAME} -- local test scaffold setup"
echo "==============================================================="
echo
echo "This sets up your Mac to dispatch the ${PROJECT_NAME} test matrix"
echo "to a Windows VM you've already provisioned. You'll need:"
echo "  * The VM's IP / hostname"
echo "  * A user account with admin rights (mounts often require admin)"
echo "  * An SSH private key that account accepts (no password prompt)"
echo "  * Required runtimes/tools as declared in harness.toml [vm.packages]"
echo

PRIOR_OR_DEFAULT_HOST="${PRIOR_HOST:-${DEFAULT_HOST}}"
prompt VM_USER "VM username" "${PRIOR_OR_DEFAULT_HOST%%@*}"
prompt VM_IP   "VM IP / hostname" "${PRIOR_OR_DEFAULT_HOST##*@}"
VM_HOST="${VM_USER}@${VM_IP}"

prompt SSH_KEY "SSH private key (blank = use ssh-agent)" "${PRIOR_KEY:-${DEFAULT_KEY}}"
prompt VM_WORKDIR "Remote workdir on the VM" "${PRIOR_WORKDIR:-${DEFAULT_WORKDIR}}"
prompt VM_IMAGE_DIR "Remote dir holding test disk images" "${PRIOR_IMAGES:-${DEFAULT_IMAGE_DIR}}"

SSH_OPTS=""
if [[ -n "${SSH_KEY}" ]]; then
    if [[ ! -f "${SSH_KEY}" ]]; then
        echo "  ! SSH key not found at: ${SSH_KEY}" >&2
        exit 1
    fi
    SSH_OPTS="-i ${SSH_KEY} -o IdentitiesOnly=yes"
fi

echo
echo "[verify] testing SSH connectivity..."
# shellcheck disable=SC2086
SSH_PROBE_OUT=$(ssh ${SSH_OPTS} -o ConnectTimeout=10 -o BatchMode=yes \
    "${VM_HOST}" 'powershell -NoProfile -Command "$PSVersionTable.OS; whoami"' 2>&1) || {
    echo "  ! SSH connection failed:"
    echo "${SSH_PROBE_OUT}" | sed 's/^/    /'
    echo
    echo "  Common fixes:"
    echo "    * ping ${VM_IP}"
    echo "    * Check the OpenSSH server service on the VM"
    echo "    * Confirm your public key is in C:\\Users\\${VM_USER}\\.ssh\\authorized_keys"
    echo "    * Try connecting manually: ssh ${SSH_OPTS} ${VM_HOST}"
    exit 1
}
echo "  ok connected:"
echo "${SSH_PROBE_OUT}" | sed 's/^/    /'

case "${SSH_PROBE_OUT}" in
    *Windows*) ;;
    *)
        echo
        echo "  ! that doesn't look like a Windows VM (no 'Windows' in OS string)."
        prompt CONTINUE_ANYWAY "Continue anyway? (y/N)" "n"
        [[ "${CONTINUE_ANYWAY}" =~ ^[Yy] ]] || exit 1
        ;;
esac

cat > "${ENV_FILE}" <<EOF
# Generated by fs-test-harness/scripts/setup-local.sh on $(date '+%Y-%m-%d %H:%M:%S').
# Sourced automatically by test-windows-matrix.sh.
# Safe to re-run setup-local.sh to regenerate.
export VM_HOST="${VM_HOST}"
export VM_WORKDIR="${VM_WORKDIR}"
export VM_IMAGE_DIR="${VM_IMAGE_DIR}"
export SSH_OPTS="${SSH_OPTS}"
EOF

GITIGNORE="${consumer_root}/.gitignore"
if [[ -f "${GITIGNORE}" ]] && ! grep -qxF '.test-env' "${GITIGNORE}"; then
    echo '.test-env' >> "${GITIGNORE}"
    echo "  ok added .test-env to .gitignore"
fi

echo
echo "==============================================================="
echo " ok Setup complete. Saved to ${ENV_FILE}"
echo
echo " Run the test matrix:"
echo "   bash ${harness_root}/scripts/test-windows-matrix.sh"
echo
echo " Run a single scenario by substring:"
echo "   bash ${harness_root}/scripts/test-windows-matrix.sh basic-ro-list"
echo
echo " List scenarios without running them:"
echo "   bash ${harness_root}/scripts/test-windows-matrix.sh --list"
echo "==============================================================="
